# This docker-compose.yml file is intended for development support. It
# is *not* meant for production.

version: '3'
name: satosa

services:
  satosa:
    # The SATOSA_IMAGE variable is defined in the .env file:
    image: ${SATOSA_IMAGE}
    command:
      - bash
      - -x
      - /custom-entrypoint.sh
    environment:
      - DEBUG_DISABLE_GUNICORN_TIMEOUTS=1
      - SATOSA_ENTITY_ID=https://tkgi-satosa.epfl.ch/tequila  # Cheating! But it works 🤷
      # - SATOSA_BASE_URL=https://tkgi-satosa.epfl.ch/tequila
    volumes:
      - ./custom-entrypoint.sh:/custom-entrypoint.sh:ro
      - ./config:/config:ro
      - ./config/attributemaps:/attributemaps:ro
      - ./data:/data:ro
      - ./proxy_conf.yaml:/proxy_conf.yaml:ro
      - ./site-python/epfl:/usr/local/lib/python3.11/site-packages/epfl:ro
      - ./tls:/tls:ro
      # - "/Users/quatrava/Library/Application Support/JetBrains/IntelliJIdea2023.1/plugins/python/debugger-eggs-output/pydevd-pycharm.egg:/pydevd-pycharm.egg:ro"
    ports:
      # We must be visible to browsers at port 443, as these days
      # Tequila doesn't belive in redirecting, nor POSTing, to any
      # other port (and while you could deal with the former using the
      # Redirector browser plug-in, the latter is more tricky.)
      - "127.0.0.1:443:8443"
volumes:
  mariadb: {}
