apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "satosa-tequila.fullname" . }}
  labels:
    {{- include "satosa-tequila.labels" . | nindent 4 }}
  {{- if eq "true" (include "hasOpenShiftBuilds" .) }}
  annotations:
    image.openshift.io/triggers: >
      [
        {
          "from": {"kind":"ImageStreamTag","name":"satosa-tequila:0.1.0"},
          "fieldPath":"spec.template.spec.containers[?(@.name==\"satosa-tequila\")].image"
        }
      ]
  {{- end }}
spec:
  {{- if not (and .Values.autoscaling .Values.autoscaling.enabled) }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "satosa-tequila.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "satosa-tequila.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "satosa-tequila.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- /*
          This points to the base image, which will have to do for the case of non-cloud-build
          (i.e. non-OpenShift) environments. On OpenShift, the `image.openshift.io/triggers`
          above, will take effect as soon as this Deployment is created (no need to wait for
          another build to succeed); in other words, the value below is all but ignored
          on OpenShift.
          */}}
          image: "{{ .Values.image.build.from.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SATOSA_BASE_URL
            value: https://{{ .Values.serve.hostname }}{{ .Values.serve.path | default "" }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /.well-known/openid-configuration
              port: http
          readinessProbe:
            httpGet:
              path: /.well-known/openid-configuration
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
