apiVersion: v1
kind: Service
metadata:
  name: {{ include "satosa-tequila.fullname" . }}
  labels:
    {{- include "satosa-tequila.labels" . | nindent 4 }}
  annotations:
    # OpenShift can create TLS key pairs as-a-service:
    service.beta.openshift.io/serving-cert-secret-name: satosa-tequila-service-tls
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  selector:
    {{- include "satosa-tequila.selectorLabels" . | nindent 4 }}
