{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "satosa-tequila.serviceAccountName" . }}
  labels:
    {{- include "satosa-tequila.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- if eq "true" (include "hasOpenShiftBuilds" .) }}
imagePullSecrets:
{{ range $index, $secret := (lookup "v1" "ServiceAccount" .Release.Namespace "default").imagePullSecrets }}
- name: {{ $secret.name }}
{{- end }}
{{- end }}
{{- end }}
