# Microservice configuration file for SATOSA
module: satosa.micro_services.attribute_modifications.AddStaticAttributes
name: AddAttributes
config:
    static_attributes:
        organisation: EPFL
        schachomeorganization: epfl.ch
        schachomeorganizationtype:
        - "urn:schac:homeOrganizationType:eu:higherEducationInstitution"
        - "urn:schac:homeOrganizationType:eu:educationInstitution"
        organizationname: EPFL
        noreduorgacronym: CH
        countryname: CH
        friendlycountryname: Switzerland
